/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthcheck */
        get: operations["healthcheck_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Authenticate with email + password, receive a session cookie.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the current session and clear its host-bound cookies.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description Return the current user and ensure a session-bound CSRF cookie exists.
         */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Courses
         * @description List courses visible to the current role scope.
         */
        get: operations["list_courses_api_v1_courses_get"];
        put?: never;
        /**
         * Create Course
         * @description Create a new course (Teacher/Admin only).
         */
        post: operations["create_course_api_v1_courses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Course
         * @description Get a single course (owner or Admin).
         */
        get: operations["get_course_api_v1_courses__course_id__get"];
        /**
         * Update Course
         * @description Update a course (owner or Admin).
         */
        put: operations["update_course_api_v1_courses__course_id__put"];
        post?: never;
        /**
         * Delete Course
         * @description Delete a course (owner or Admin).
         */
        delete: operations["delete_course_api_v1_courses__course_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Archive Course
         * @description Archive an ACTIVE course (owner or Admin).
         */
        post: operations["archive_course_api_v1_courses__course_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Assignments
         * @description List assignments visible to the current user.
         */
        get: operations["list_assignments_api_v1_courses__course_id__assignments_get"];
        put?: never;
        /**
         * Create Assignment
         * @description Create a new assignment in a course (owner/Admin).
         */
        post: operations["create_assignment_api_v1_courses__course_id__assignments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}/assignments/{assignment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Assignment
         * @description Get a single assignment (respects student visibility).
         */
        get: operations["get_assignment_api_v1_courses__course_id__assignments__assignment_id__get"];
        /**
         * Update Assignment
         * @description Update a DRAFT assignment (owner/Admin).
         */
        put: operations["update_assignment_api_v1_courses__course_id__assignments__assignment_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}/assignments/{assignment_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Assignment
         * @description Publish a DRAFT assignment (DRAFT → OPEN).
         */
        post: operations["publish_assignment_api_v1_courses__course_id__assignments__assignment_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}/assignments/{assignment_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Close Assignment
         * @description Close an OPEN assignment (OPEN → CLOSED).
         */
        post: operations["close_assignment_api_v1_courses__course_id__assignments__assignment_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rubrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rubrics
         * @description List rubric versions. Admin sees all; Teacher sees own.
         */
        get: operations["list_rubrics_api_v1_rubrics_get"];
        put?: never;
        /**
         * Create Rubric
         * @description Create a new rubric version (Teacher/Admin).
         */
        post: operations["create_rubric_api_v1_rubrics_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rubrics/{rubric_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rubric
         * @description Get a single rubric version (owner/Admin).
         */
        get: operations["get_rubric_api_v1_rubrics__rubric_id__get"];
        /**
         * Update Rubric
         * @description Update a DRAFT rubric version (owner/Admin).
         */
        put: operations["update_rubric_api_v1_rubrics__rubric_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rubrics/{rubric_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Publish Rubric
         * @description Publish a DRAFT rubric version.
         */
        post: operations["publish_rubric_api_v1_rubrics__rubric_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rubrics/{rubric_id}/new-version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create New Version
         * @description Create a new DRAFT version from a published rubric.
         */
        post: operations["create_new_version_api_v1_rubrics__rubric_id__new_version_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rubrics/{rubric_id}/criteria": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Criteria
         * @description List criteria for a rubric version.
         */
        get: operations["list_criteria_api_v1_rubrics__rubric_id__criteria_get"];
        put?: never;
        /**
         * Add Criterion
         * @description Add a criterion to a DRAFT rubric version.
         */
        post: operations["add_criterion_api_v1_rubrics__rubric_id__criteria_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rubrics/{rubric_id}/criteria/{criterion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Criterion
         * @description Update a criterion on a DRAFT rubric version.
         */
        put: operations["update_criterion_api_v1_rubrics__rubric_id__criteria__criterion_id__put"];
        post?: never;
        /**
         * Delete Criterion
         * @description Delete a criterion from a DRAFT rubric version.
         */
        delete: operations["delete_criterion_api_v1_rubrics__rubric_id__criteria__criterion_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignments/{assignment_id}/uploads/presign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Presign Upload */
        post: operations["presign_upload_api_v1_assignments__assignment_id__uploads_presign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/document-versions/{version_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Upload */
        post: operations["complete_upload_api_v1_document_versions__version_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis-jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis Job */
        get: operations["get_analysis_job_api_v1_analysis_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analysis-jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Analysis Job */
        post: operations["retry_analysis_job_api_v1_analysis_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/courses/{course_id}/submission-queue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Submission Queue */
        get: operations["submission_queue_api_v1_courses__course_id__submission_queue_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{submission_id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Submission Evidence */
        get: operations["submission_evidence_api_v1_submissions__submission_id__evidence_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{submission_id}/review-lock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Acquire Submission Review Lock */
        post: operations["acquire_submission_review_lock_api_v1_submissions__submission_id__review_lock_post"];
        /** Release Submission Review Lock */
        delete: operations["release_submission_review_lock_api_v1_submissions__submission_id__review_lock_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{submission_id}/review-lock/heartbeat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Heartbeat Submission Review Lock */
        put: operations["heartbeat_submission_review_lock_api_v1_submissions__submission_id__review_lock_heartbeat_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{submission_id}/review-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission Review Draft */
        get: operations["get_submission_review_draft_api_v1_submissions__submission_id__review_draft_get"];
        /** Put Submission Review Draft */
        put: operations["put_submission_review_draft_api_v1_submissions__submission_id__review_draft_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/document-versions/{version_id}/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Document Version */
        post: operations["approve_document_version_api_v1_document_versions__version_id__approve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/document-versions/{version_id}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Publish Document Version */
        post: operations["publish_document_version_api_v1_document_versions__version_id__publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assignments/{assignment_id}/document-versions/bulk-publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bulk Publish Document Versions */
        post: operations["bulk_publish_document_versions_api_v1_assignments__assignment_id__document_versions_bulk_publish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/published-results/{published_result_id}/unpublish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unpublish Published Result */
        post: operations["unpublish_published_result_api_v1_published_results__published_result_id__unpublish_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{submission_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Submission Versions */
        get: operations["list_submission_versions_api_v1_submissions__submission_id__versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{submission_id}/versions/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Compare Submission Versions */
        get: operations["compare_submission_versions_api_v1_submissions__submission_id__versions_compare_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissions/{submission_id}/published-result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Submission Published Result */
        get: operations["get_submission_published_result_api_v1_submissions__submission_id__published_result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisJobResponse */
        AnalysisJobResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /**
             * Rubric Version Id
             * Format: uuid
             */
            rubric_version_id: string;
            /** Status */
            status: string;
            /** Attempt Count */
            attempt_count: number;
            /** Max Attempts */
            max_attempts: number;
            /** Error Code */
            error_code: string | null;
            /** Error Detail */
            error_detail: string | null;
            /**
             * Queued At
             * Format: date-time
             */
            queued_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
        };
        /** ApprovalResponse */
        ApprovalResponse: {
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /** Status */
            status: string;
            /**
             * Approved At
             * Format: date-time
             */
            approved_at: string;
        };
        /** AssignmentCreate */
        AssignmentCreate: {
            /**
             * Rubric Version Id
             * Format: uuid
             */
            rubric_version_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            /**
             * Max Submissions
             * @default 3
             */
            max_submissions: number;
        };
        /** AssignmentResponse */
        AssignmentResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Course Id
             * Format: uuid
             */
            course_id: string;
            /**
             * Created By Teacher Id
             * Format: uuid
             */
            created_by_teacher_id: string;
            /**
             * Rubric Version Id
             * Format: uuid
             */
            rubric_version_id: string;
            /** Title */
            title: string;
            /** Description */
            description: string | null;
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            /** Max Submissions */
            max_submissions: number;
            /** Status */
            status: string;
            /** Published At */
            published_at: string | null;
            /** Closed At */
            closed_at: string | null;
            /** Revision */
            revision: number;
        };
        /** AssignmentUpdate */
        AssignmentUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Due At */
            due_at?: string | null;
            /** Max Submissions */
            max_submissions?: number | null;
            /** Rubric Version Id */
            rubric_version_id?: string | null;
        };
        /** BBox */
        BBox: {
            /** X0 */
            x0: number;
            /** Top */
            top: number;
            /** X1 */
            x1: number;
            /** Bottom */
            bottom: number;
        };
        /** BulkPublishRequest */
        BulkPublishRequest: {
            /** Version Ids */
            version_ids: string[];
            /** Reason */
            reason: string;
        };
        /** BulkPublishResponse */
        BulkPublishResponse: {
            /** Results */
            results: components["schemas"]["PublishedResultResponse"][];
        };
        /** CompletionResponse */
        CompletionResponse: {
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /**
             * Analysis Job Id
             * Format: uuid
             */
            analysis_job_id: string;
            /** Status */
            status: string;
        };
        /** CourseCreate */
        CourseCreate: {
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Term */
            term: string;
        };
        /** CourseResponse */
        CourseResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Name */
            name: string;
            /** Term */
            term: string;
            status: components["schemas"]["CourseStatus"];
            /**
             * Owner Teacher Id
             * Format: uuid
             */
            owner_teacher_id: string;
            /** Revision */
            revision: number;
        };
        /**
         * CourseStatus
         * @enum {string}
         */
        CourseStatus: "ACTIVE" | "ARCHIVED";
        /** CourseUpdate */
        CourseUpdate: {
            /** Name */
            name?: string | null;
            /** Term */
            term?: string | null;
        };
        /** CriterionCreate */
        CriterionCreate: {
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Weight */
            weight: number | string;
            /** Position */
            position: number;
            /**
             * Evaluation Method
             * @default AI
             */
            evaluation_method: string;
            /** Scope */
            scope?: string | null;
            /**
             * Is Enabled
             * @default true
             */
            is_enabled: boolean;
            /** Levels */
            levels?: {
                [key: string]: unknown;
            }[];
            /** Evaluator Config */
            evaluator_config?: {
                [key: string]: unknown;
            };
            /** Evidence Requirements */
            evidence_requirements?: {
                [key: string]: unknown;
            };
        };
        /** CriterionResponse */
        CriterionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Criterion Id
             * Format: uuid
             */
            criterion_id: string;
            /**
             * Rubric Version Id
             * Format: uuid
             */
            rubric_version_id: string;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /** Description */
            description: string;
            /** Scope */
            scope: string | null;
            /** Weight */
            weight: string;
            /** Position */
            position: number;
            /** Is Enabled */
            is_enabled: boolean;
            /** Evaluation Method */
            evaluation_method: string;
            /** Levels */
            levels: {
                [key: string]: unknown;
            }[];
            /** Evaluator Config */
            evaluator_config: {
                [key: string]: unknown;
            };
            /** Evidence Requirements */
            evidence_requirements: {
                [key: string]: unknown;
            };
            /** Revision */
            revision: number;
        };
        /** CriterionUpdate */
        CriterionUpdate: {
            /** Title */
            title?: string | null;
            /** Description */
            description?: string | null;
            /** Weight */
            weight?: number | string | null;
            /** Position */
            position?: number | null;
            /** Evaluation Method */
            evaluation_method?: string | null;
            /** Scope */
            scope?: string | null;
            /** Is Enabled */
            is_enabled?: boolean | null;
            /** Levels */
            levels?: {
                [key: string]: unknown;
            }[] | null;
            /** Evaluator Config */
            evaluator_config?: {
                [key: string]: unknown;
            } | null;
            /** Evidence Requirements */
            evidence_requirements?: {
                [key: string]: unknown;
            } | null;
        };
        /** EvidenceResponse */
        EvidenceResponse: {
            /**
             * Document Ir Id
             * Format: uuid
             */
            document_ir_id: string;
            /** Element Id */
            element_id: string;
            /** Page Number */
            page_number: number;
            bbox: components["schemas"]["BBox"];
        };
        /** EvidenceWorkspaceResponse */
        EvidenceWorkspaceResponse: {
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /** Findings */
            findings: components["schemas"]["FindingResponse"][];
        };
        /** FindingResponse */
        FindingResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Criterion Version Id
             * Format: uuid
             */
            criterion_version_id: string;
            /** Severity */
            severity: string;
            /** Description */
            description: string;
            /** Suggestion */
            suggestion: string | null;
            /** Proposed Score */
            proposed_score: string | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceResponse"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** LoginRequest */
        LoginRequest: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** PresignRequest */
        PresignRequest: {
            /** Filename */
            filename: string;
            /** Content Type */
            content_type: string;
            /** Size Bytes */
            size_bytes: number;
            /** Sha256 */
            sha256: string;
        };
        /** PresignResponse */
        PresignResponse: {
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /** Object Key */
            object_key: string;
            /** Upload Url */
            upload_url?: string | null;
            /** Fields */
            fields?: {
                [key: string]: string;
            } | null;
            /** Expires In */
            expires_in?: number | null;
            /** Status */
            status: string;
            /**
             * Reused
             * @default false
             */
            reused: boolean;
            /** Analysis Job Id */
            analysis_job_id?: string | null;
        };
        /** PublishRequest */
        PublishRequest: {
            /** Reason */
            reason: string;
        };
        /** PublishedFindingResponse */
        PublishedFindingResponse: {
            /**
             * Criterion Version Id
             * Format: uuid
             */
            criterion_version_id: string;
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            /** Score */
            score: string | null;
            /** Description */
            description: string;
            /** Suggestion */
            suggestion: string | null;
            /** Evidence */
            evidence: components["schemas"]["EvidenceResponse"][];
        };
        /** PublishedResultResponse */
        PublishedResultResponse: {
            /**
             * Published Result Id
             * Format: uuid
             */
            published_result_id: string;
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /** Version Number */
            version_number: number;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Comment */
            comment: string;
            /** Findings */
            findings: components["schemas"]["PublishedFindingResponse"][];
        };
        /** QueueLockResponse */
        QueueLockResponse: {
            /**
             * Reviewer User Id
             * Format: uuid
             */
            reviewer_user_id: string;
            /** Reviewer Display Name */
            reviewer_display_name: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
        };
        /**
         * QueueSort
         * @enum {string}
         */
        QueueSort: "asc" | "desc";
        /**
         * QueueStatus
         * @enum {string}
         */
        QueueStatus: "UNREVIEWED" | "REVIEWED" | "ERROR";
        /** ReviewDecisionRequest */
        ReviewDecisionRequest: {
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            decision: components["schemas"]["ReviewDecisionType"];
            /** Edited Description */
            edited_description?: string | null;
            /** Final Score */
            final_score?: number | string | null;
            /** Reason */
            reason?: string | null;
        };
        /** ReviewDecisionResponse */
        ReviewDecisionResponse: {
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            decision: components["schemas"]["ReviewDecisionType"];
            /** Edited Description */
            edited_description: string | null;
            /** Final Score */
            final_score: string | null;
            /** Reason */
            reason: string | null;
        };
        /**
         * ReviewDecisionType
         * @enum {string}
         */
        ReviewDecisionType: "ACCEPT" | "EDIT" | "REJECT";
        /** ReviewDraftRequest */
        ReviewDraftRequest: {
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /** Revision */
            revision: number;
            /**
             * Comment
             * @default
             */
            comment: string;
            /** Decisions */
            decisions?: components["schemas"]["ReviewDecisionRequest"][];
        };
        /** ReviewDraftResponse */
        ReviewDraftResponse: {
            /** Id */
            id: string | null;
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
            /** Document Version Id */
            document_version_id: string | null;
            /**
             * Reviewer User Id
             * Format: uuid
             */
            reviewer_user_id: string;
            /** Revision */
            revision: number;
            /** Comment */
            comment: string;
            /** Decisions */
            decisions: components["schemas"]["ReviewDecisionResponse"][];
        };
        /** ReviewLockResponse */
        ReviewLockResponse: {
            /** Acquired */
            acquired: boolean;
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
            /** Reviewer User Id */
            reviewer_user_id?: string | null;
            /** Reviewer Display Name */
            reviewer_display_name?: string | null;
            /** Expires At */
            expires_at?: string | null;
        };
        /** RubricVersionCreate */
        RubricVersionCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Calculation Method
             * @default WEIGHTED_SUM
             */
            calculation_method: string;
        };
        /** RubricVersionResponse */
        RubricVersionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Rubric Id
             * Format: uuid
             */
            rubric_id: string;
            /** Version Number */
            version_number: number;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Status */
            status: string;
            /** Calculation Method */
            calculation_method: string;
            /** Total Weight */
            total_weight: string;
            /**
             * Owner User Id
             * Format: uuid
             */
            owner_user_id: string;
            /**
             * Created By User Id
             * Format: uuid
             */
            created_by_user_id: string;
            /** Source Version Id */
            source_version_id: string | null;
            /** Published At */
            published_at: string | null;
            /** Revision */
            revision: number;
        };
        /** RubricVersionUpdate */
        RubricVersionUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Calculation Method */
            calculation_method?: string | null;
        };
        /** SubmissionQueueItem */
        SubmissionQueueItem: {
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
            /** Document Version Id */
            document_version_id: string | null;
            /**
             * Student Id
             * Format: uuid
             */
            student_id: string;
            /** Document Status */
            document_status: string | null;
            queue_status: components["schemas"]["QueueStatus"];
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            review_lock?: components["schemas"]["QueueLockResponse"] | null;
        };
        /** SubmissionQueueResponse */
        SubmissionQueueResponse: {
            /** Items */
            items: components["schemas"]["SubmissionQueueItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** SubmissionVersionListResponse */
        SubmissionVersionListResponse: {
            /** Items */
            items: components["schemas"]["SubmissionVersionResponse"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** SubmissionVersionResponse */
        SubmissionVersionResponse: {
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /** Version Number */
            version_number: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            processing_status: components["schemas"]["VersionProcessingStatus"];
            publication_status?: components["schemas"]["VersionPublicationStatus"] | null;
            /** Published Result Id */
            published_result_id?: string | null;
            /** Published At */
            published_at?: string | null;
        };
        /** UnpublishRequest */
        UnpublishRequest: {
            /** Reason */
            reason: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Display Name */
            display_name: string;
            /** Roles */
            roles: string[];
            /** Status */
            status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VersionComparisonFindingResponse */
        VersionComparisonFindingResponse: {
            /**
             * Criterion Version Id
             * Format: uuid
             */
            criterion_version_id: string;
            /**
             * Finding Id
             * Format: uuid
             */
            finding_id: string;
            /** Score */
            score: string | null;
            decision: components["schemas"]["ReviewDecisionType"] | null;
            /** Evidence Count */
            evidence_count: number;
        };
        /** VersionComparisonResponse */
        VersionComparisonResponse: {
            /**
             * Submission Id
             * Format: uuid
             */
            submission_id: string;
            left: components["schemas"]["VersionComparisonSideResponse"];
            right: components["schemas"]["VersionComparisonSideResponse"];
        };
        /** VersionComparisonSideResponse */
        VersionComparisonSideResponse: {
            /**
             * Document Version Id
             * Format: uuid
             */
            document_version_id: string;
            /** Version Number */
            version_number: number;
            /** Comment */
            comment: string;
            /** Findings */
            findings: components["schemas"]["VersionComparisonFindingResponse"][];
        };
        /**
         * VersionProcessingStatus
         * @enum {string}
         */
        VersionProcessingStatus: "QUEUED" | "PROCESSING" | "AWAITING_REVIEW" | "ERROR";
        /**
         * VersionPublicationStatus
         * @enum {string}
         */
        VersionPublicationStatus: "PUBLISHED" | "UNPUBLISHED";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthcheck_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    list_courses_api_v1_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"][];
                };
            };
        };
    };
    create_course_api_v1_courses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_course_api_v1_courses__course_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_course_api_v1_courses__course_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_course_api_v1_courses__course_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_course_api_v1_courses__course_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_assignments_api_v1_courses__course_id__assignments_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_assignment_api_v1_courses__course_id__assignments_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_assignment_api_v1_courses__course_id__assignments__assignment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                assignment_id: string;
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_assignment_api_v1_courses__course_id__assignments__assignment_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_assignment_api_v1_courses__course_id__assignments__assignment_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_assignment_api_v1_courses__course_id__assignments__assignment_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                course_id: string;
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rubrics_api_v1_rubrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubricVersionResponse"][];
                };
            };
        };
    };
    create_rubric_api_v1_rubrics_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RubricVersionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubricVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rubric_api_v1_rubrics__rubric_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubricVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rubric_api_v1_rubrics__rubric_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RubricVersionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubricVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_rubric_api_v1_rubrics__rubric_id__publish_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubricVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_new_version_api_v1_rubrics__rubric_id__new_version_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RubricVersionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_criteria_api_v1_rubrics__rubric_id__criteria_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_criterion_api_v1_rubrics__rubric_id__criteria_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriterionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_criterion_api_v1_rubrics__rubric_id__criteria__criterion_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criterion_id: string;
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CriterionUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CriterionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_criterion_api_v1_rubrics__rubric_id__criteria__criterion_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                criterion_id: string;
                rubric_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    presign_upload_api_v1_assignments__assignment_id__uploads_presign_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PresignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PresignResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_upload_api_v1_document_versions__version_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_job_api_v1_analysis_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_analysis_job_api_v1_analysis_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submission_queue_api_v1_courses__course_id__submission_queue_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["QueueStatus"] | null;
                sort?: components["schemas"]["QueueSort"];
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                course_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionQueueResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submission_evidence_api_v1_submissions__submission_id__evidence_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceWorkspaceResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acquire_submission_review_lock_api_v1_submissions__submission_id__review_lock_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewLockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    release_submission_review_lock_api_v1_submissions__submission_id__review_lock_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    heartbeat_submission_review_lock_api_v1_submissions__submission_id__review_lock_heartbeat_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewLockResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_review_draft_api_v1_submissions__submission_id__review_draft_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_submission_review_draft_api_v1_submissions__submission_id__review_draft_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewDraftRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewDraftResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_document_version_api_v1_document_versions__version_id__approve_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    publish_document_version_api_v1_document_versions__version_id__publish_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                version_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_publish_document_versions_api_v1_assignments__assignment_id__document_versions_bulk_publish_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                assignment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkPublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkPublishResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unpublish_published_result_api_v1_published_results__published_result_id__unpublish_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                published_result_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UnpublishRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_submission_versions_api_v1_submissions__submission_id__versions_get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionVersionListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_submission_versions_api_v1_submissions__submission_id__versions_compare_get: {
        parameters: {
            query: {
                left_version_id: string;
                right_version_id: string;
            };
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionComparisonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_submission_published_result_api_v1_submissions__submission_id__published_result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                submission_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublishedResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
